kind = "mobile"
previewPath = "/"
title = "Android IDE"
version = "1.0.0"
id = "artifacts/android-ide"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 25641

[services.development]
run = "pnpm --filter @workspace/android-ide run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/android-ide", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/android-ide", "run", "serve" ]

[services.env]
PORT = "25641"
BASE_PATH = "/"
